name: Update Index

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Run index builder
      run: python3 .github/scripts/update_index.py

    - name: Commit updated README.md
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-update problem index"
